export const ORDER_STATUS = Object.freeze({
  WAITING: 'WAITING',
  WAITING_DELIVERY: 'WAITING_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELED: 'CANCELED',
  RETURNS: 'RETURNS',
  ERROR: 'ERROR',
  ON_DELIVERY: 'ON_DELIVERY',
  DONE: 'DONE',
  WAITING_CONFIRM_RETURNS: 'WAITING_CONFIRM_RETURNS',
  REJECT_RETURNS: 'REJECT_RETURNS'
})
